export const products = {
  items: [
    {
        id: '001',
        img: 'img/big-azure-vaze.jpg',
        name: 'Atari',
        size: 'Big',
        color: 'azure',
        type: 'vase',
        creator: 'Jango',
        year: 1988,
        popular: true,
        amount: 5,
        price: 1560,
    },
    {
      id: '002',
      img: 'img/small-midnightblue-vaze.jpg',
      name: 'Dame',
      size: 'Small',
      color: 'midnightblue',
      type: 'vase',
      creator: 'Szuki',
      year: 1996,
      popular: false,
      amount: 23,
      price: 876,
    },
    {
      id: '003',
      img: 'img/medium-mistyrose-pot.jpg',
      name: 'Gote',
      size: 'Medium',
      color: 'mistyrose',
      type: 'pot',
      creator: 'Western',
      year: 1992,
      popular: false,
      amount: 18,
      price: 954,
    },
    {
      id: '004',
      img: 'img/big-lightskyblue-plate.jpg',
      name: 'Kamoku',
      size: 'Big',
      color: 'lightskyblue',
      type: 'plate',
      creator: 'Yaki',
      year: 1989,
      popular: true,
      amount: 3,
      price: 1184,
    },
    {
      id: '005',
      img: 'img/big-ivory-vaze.jpg',
      name: 'Keima',
      size: 'Big',
      color: 'ivory',
      type: 'vaze',
      creator: 'Yaki',
      year: 1998,
      popular: false,
      amount: 23,
      price: 883,
    },
    {
      id: '006',
      img: 'img/small-seashell-pot.jpg',
      name: 'Miai',
      size: 'Small',
      color: 'seashell',
      type: 'pot',
      creator: 'Szuki',
      year: 1993,
      popular: false,
      amount: 19,
      price: 988,
    },
    {
      id: '007',
      img: 'img/medium-saddlebrown-pot.jpg',
      name: 'Sansan',
      size: 'Medium',
      color: 'saddlebrown',
      type: 'pot',
      creator: 'Jango',
      year: 1995,
      popular: false,
      amount: 26,
      price: 852,
    },
    {
      id: '008',
      img: 'img/medium-midnightblue-plate.jpg',
      name: 'Simari',
      size: 'Medium',
      color: 'midnightblue',
      type: 'plate',
      creator: 'Western',
      year: 1990,
      popular: false,
      amount: 0,
      price: 903,
    },
]
}